# Generated by Django 2.2.8 on 2022-12-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.PositiveIntegerField()),
                ('title', models.TextField()),
                ('publishYear', models.PositiveIntegerField()),
                ('pages', models.PositiveIntegerField()),
                ('author', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
    ]
