# Generated by Django 2.2.8 on 2022-12-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.PositiveIntegerField()),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.PositiveIntegerField()),
                ('borrow_date', models.TextField()),
                ('return_date', models.TextField()),
                ('isbn', models.PositiveIntegerField()),
                ('title', models.TextField()),
            ],
        ),
    ]
